

name: Flask API

on:
  push:
    branches:
      - main

jobs:
  run_flask_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install Flask
      - name: Run Flask API
        run: |
          flask run --host=0.0.0.0 --port=$PORT
        env:
          PORT: 5000
